# example for 1.0 cod2 server
version: '3.7'
services:
  myserver:
    image: lonsofore/cod2:1.0
    container_name: myserver
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 28960:28960
      - 28960:28960/udp
    volumes:
      - ~/cod2/myserver:/cod2/myserver
      - ~/cod2/main:/cod2/main
      - ~/cod2/Library:/cod2/.callofduty2/myserver/Library
    environment:
      PARAMS_BEFORE: "+exec myserver.cfg"
      COD2_SET_fs_homepath: "/cod2/.callofduty2/"
      COD2_SET_fs_game: "myserver"
      COD2_SET_dedicated: 2
      COD2_SET_net_port: 28960
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
