name: ci

on:
  push:
    branches: master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push images
        id: build
        run: ./build_all.sh lonsofore cod2 1

      - name: Login to Github
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push images
        id: build
        run: ./build_all.sh docker.pkg.github.com lonsofore/cod2docker/cod2 1
